content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4e8116e-46fb-474c-b8d0-14be9d18f489.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4e8116e-46fb-474c-b8d0-14be9d18f489.jpg
    metadata:
      description: ''
      '@context': 'http://schema.org'
      related: []
      author: []
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        favicon: null
      app_links: []
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
content_rating:
  adult: false
layout_spectrum: 1
github: true
name: Cities
author: {}
analytics: {}
opengraph: {}
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2191489
color:
  brandStrength: 1
  lightness: 0.3106383
  saturation: 0.7148936
  rhythmicContrast: 1
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
