layout_spectrum: 0.9965783258149455
typography_spectrum: 0.37544801835975805
color:
  brandStrength: 0.04772908280861776
  lightness: 0.676569479522987
  saturation: 0.31100636745498766
  rhythmicContrast: 0.6249484693883264
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
coverPrefs:
  filter: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4e8116e-46fb-474c-b8d0-14be9d18f489.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4e8116e-46fb-474c-b8d0-14be9d18f489.jpg
    metadata:
      description: ''
      '@context': 'http://schema.org'
      related: []
      author: []
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        favicon: null
      app_links: []
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
content_rating:
  adult: false
github: true
name: Cities
author: {}
analytics: {}
opengraph: {}
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
